language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
matrix:
  allow_failures:
    - python: "3.5"
before_install:
    - rm Pipfile.lock || true
    - "pip install pipenv"
    - "sudo apt-get install -y sqlite3 fftw3 libfftw3-dev"
install:
    - "pipenv sync"
script: ./run_tests.sh
